server:
  port: 8080

spring:
  application:
    name: ims-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ims
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
  flyway:
    enabled: false

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ims.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.ims: debug
    com.baomidou.mybatisplus: debug