server:
  port: 8080

spring:
  application:
    name: ims-single
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ims;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
  sql:
    init:
      mode: always
  flyway:
    enabled: false

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ims.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.ims: debug
    com.baomidou.mybatisplus: debug